tap "caskroom/drivers"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "cask"

cask "xquartz"
cask "clipy"
cask "docker"
cask "enpass"
cask "firefox"
cask "font-fira-code"
cask "font-roboto-mono"
cask "google-japanese-ime"
cask "iterm2"
cask "minikube"
cask "postman"
cask "slack"
cask "tableplus"
cask "visual-studio-code"
cask "zoomus"

brew "awscli"
brew "bash"
brew "docker-compose"
brew "emacs"
brew "fontconfig"
brew "fzf"
brew "kubernetes-cli"
brew "minikube"
brew "reattach-to-user-namespace"
brew "stow"
brew "tmux"
brew "wget"