set -g @bg      "#1C1C1C"
set -g @surface "#2E2E2C"
set -g @surface2 "#162032"
set -g @border  "#858E8E"
set -g @fg      "#E8E5DE"
set -g @accent  "#DD4B29"
set -g @accent2 "#0070BA"
set -g @success "#016937"
set -g @error   "#C0282C"
set -g @warning "#FAB513"
set -g @border2 "#A9875A"
