#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           72

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true

(sleep 1s && wal -R) &
(sleep 1s && picom -b --config $HOME/.config/picom.conf) &
(sleep 1s && $HOME/.config/polybar/launch.sh) &
(sleep 1s && libinput-gestures) &
(sleep 1s && dunst -conf $HOME/.cache/wal/dunstrc) &
(sleep 1s && outer-display-only) &
(sleep 1s && fcitx-autostart) &
(sleep 1s && xss-lock -- xscreensaver-command -lock) &
(sleep 1s && clipcatd) &
