#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

(sleep 1s && wal -R) &
(sleep 1s && picom -b) &
(sleep 1s && $HOME/.config/polybar/launch.sh) &
(sleep 1s && libinput-gestures) &
(sleep 1s && launch-dunst) &
(sleep 1s && outer-display-only) &
(sleep 1s && fcitx-autostart) &
(sleep 1s && xss-lock -- xscreensaver-command -lock) &
