width = 320
height = 720
force_window = false
font = "Roboto Mono Bold"
font_size = 16
bg_color = 0x{background.strip}ff
font_color = 0x{foreground.strip}ff

[input_text]
font_color = 0x{background.strip}ff
bg_color = 0x{foreground.strip}ff
margin = "16"
padding = "4 8"

[list_items]
font_color = 0x{foreground.strip}ff
selected_font_color = 0x{color1.strip}ff
match_color = 0x{color2.strip}ff
margin = "8 16"
hide_actions = false
action_left_margin = 16
item_spacing = 16
icon_spacing = 8
[icon]
size = 16
theme = "Tela circle dark"