width = 720
height = 480
force_window = false
font = "Noto Sans CJK JP"
font_size = 16
bg_color = 0x{background.strip}ff
font_color = 0x{foreground.strip}ff

[list_items]
font_color = 0x{foreground.strip}ff
selected_font_color = 0x{color1.strip}ff
match_color = 0x{color2.strip}ff
margin = "8 16"
hide_actions = false
action_left_margin = 0
item_spacing = 16
