# colors (Generated by 'wal')
window.*.title.bg.color: {{BACKGROUND}}
window.*.label.text.color: {{FOREGROUND}}
window.*.button.*.image.color: {{BACKGROUND}}

# Borders
window.handle.width: 0
window.client.padding.width: 0
border.width: 0

# Title
padding.width: 50
padding.height: 8
window.*.title.bg: Solid Flat
window.*.*.bg: Parentrelative
window.label.text.justify: center