set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g default-shell /bin/bash
set -g default-command "/bin/bash --login"

set -g escape-time 0
set -g pane-border-status bottom
set -g pane-border-format ""
set -g pane-border-style fg="black"
set -g pane-active-border-style fg="black",bg="black"

set -g status-justify left
set -g status-bg black
set -g status-fg colour8
set -g status-right-length 30
set -g status-left-length 60
set -g status-interval 1
set -g status-left  '#{b:pane_current_path} | #[fg=blue,bold]#(cd #{pane_current_path}; tmux_branchname) #[default]|'
set -g status-right '#(date "+%H:%M") | #H'
set-window-option -g window-status-format " #W  |"
set-window-option -g window-status-current-format "#[fg=red,bold] ● #W #[default] |"


set -g base-index 1
setw -g pane-base-index 1

set-option -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

bind r source-file ~/.tmux.conf \; display "😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺 😺"
bind c new-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind '"' split-window -vc "#{pane_current_path}"
bind-key -T copy-mode C-c send-keys -X copy-pipe "tmux save-buffer - | clip" \; display-message "copied to system clipboard" \; send-keys -X

bind Space display-menu -T "#[align=centre] tmux " -x C -y C -- \
  "-Pane-"            ""  "" \
  "Split horizontal"  "%" "split-window -hc '#{pane_current_path}'" \
  "Split vertical"    '"' "split-window -vc '#{pane_current_path}'" \
  "Select left"       "h" "select-pane -L" \
  "Select down"       "j" "select-pane -D" \
  "Select up"         "k" "select-pane -U" \
  "Select right"      "l" "select-pane -R" \
  "Next pane"         "o" "select-pane -t :.+" \
  "Zoom toggle"       "z" "resize-pane -Z" \
  "Kill pane"         "x" "kill-pane" \
  "" \
  "-Window-"          ""  "" \
  "New window"        "c" "new-window -c '#{pane_current_path}'" \
  "Next window"       "n" "next-window" \
  "Prev window"       "p" "previous-window" \
  "Rename window"     "," "command-prompt -I '#W' 'rename-window %%'" \
  "" \
  "-Session-"         ""  "" \
  "Detach"            "d" "detach-client" \
  "Choose session"    "s" "choose-tree -Zs" \
  "Reload config"     "r" "source-file ~/.tmux.conf"

set-window-option -g mode-keys emacs