set -g @background "#1C1C1C"
set -g @foreground "#E8E5DE"
set -g @color0  "#1C1C1C"
set -g @color1  "#F04A38"
set -g @color2  "#35B36B"
set -g @color3  "#FFD23F"
set -g @color4  "#3D7DD8"
set -g @color5  "#B25FC0"
set -g @color6  "#38A6B8"
set -g @color7  "#4C4C48"
set -g @color8  "#7A776F"
set -g @color9  "#FF7A63"
set -g @color10 "#5DD08C"
set -g @color11 "#FFDD6B"
set -g @color12 "#6B9CE0"
set -g @color13 "#CC8AD6"
set -g @color14 "#6BC4D3"
set -g @color15 "#F5F3EE"
