;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-pair-delete-pair
        elscreen-previous
        indent-for-tab-command
        ))

(setq mc/cmds-to-run-once
      '(
        fill-paragraph
        slim-electric-backspace
        ))
