name: Test

on: push
  # schedule:
  #   - cron:  '0 0 * * SAT'

jobs:
  arch:
    name: Arch Linux
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Install make
        run: pacman -Syy && pacman -S --noconfirm make
      - name: Run make
        run: make SKIP_CONFIRM=true
  # macos:
  #   name: macOS
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout codes
  #       uses: actions/checkout@v2
  #     - name: Select Xcode version
  #       run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
  #     - name: Clean
  #       run: sudo rm /usr/local/bin/aws*
  #     - name: Run make
  #       run: make SKIP_CONFIRM=true
