name: Test

on: push
  # schedule:
  #   - cron:  '0 0 * * SAT'

jobs:
  arch:
    name: Arch Linux
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Install make and sudo
        run: pacman -Syy && pacman -S --noconfirm make sudo
      - name: Create test user
        run: |
          TEST_UID=1000
          TEST_USER=tester
          TEST_GROUP=wheel
          useradd -m -s $SHELL -u $TEST_UID -g wheel $TEST_USER
      - name: Run make
        run: su tester -c 'make SKIP_CONFIRM=true'
  # macos:
  #   name: macOS
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout codes
  #       uses: actions/checkout@v2
  #     - name: Select Xcode version
  #       run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
  #     - name: Clean
  #       run: sudo rm /usr/local/bin/aws*
  #     - name: Run make
  #       run: make SKIP_CONFIRM=true
